### ISSUE TITLE
Fails to load with error: No signal 'maximize' on object 'ShellWM'

### ISSUE THREAD

**Issue by skewty** [luispabon/maximus-gnome-shell#15] opened 2016-08-08 16:26 UTC
Randomly the extension fails to load with error: No signal 'maximize' on object 'ShellWM'.

Uninstalling the extension, rebooting and re-installing the extension gets it working again.
Running: Ubuntu Gnome 16.04.1 with 3.20 PPA

 I don't ever change the extension options or the white/black list so I doubt it is file corruption.

Is there anything I can do to assist in tracking down this issue?

**Comment by luispabon** [comment] 2016-09-28 16:12
@skewty if you could please check whether it's related to #16, that'd be great

**Comment by skewty** [comment] 2016-10-24 18:48
I always use alternate mode.  So it isn't related.

I am encountering this issue again after switching to Wayland.
I can't seem to get Maximus to start at all in a Wayland session.  My old trick of getting it to work when it wouldn't start was Alt+F2+r.  It doesn't work with Wayland though.

I wasn't using Maximus for a while due to this issue and switched to this script I wrote:

``` bash
#!/bin/bash

#
# This script will toggle the active window's decorations
#

WIN_ID=`xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5`
DECORATED="0x2,0x0,0x1,0x0,0x0"
UNDECORATED="0x2,0x0,0x0,0x0,0x0"

if [[ $(xprop -id "$WIN_ID" _MOTIF_WM_HINTS | cut -d ' ' -f 5 | cut -c 1) = "1" ]]; then
  xprop -id "$WIN_ID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "$UNDECORATED"  
else
  xprop -id "$WIN_ID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "$DECORATED"
fi

WIN_NAME=`wmctrl -l | grep "0x[0]*${WIN_ID:2}" | cut -d ' ' -f 5-`

wmctrl -a "$WIN_NAME"  # re-activate the window

```

**Comment by luispabon** [comment] 2017-04-18 09:34
Duplicate of #19.

**Closed as completed by luispabon** 2017-04-18 09:34 UTC
